### ISSUE TITLE
Missing source/Dependencies

### ISSUE THREAD

**Issue by ankurmitujjain** [kmader/tipl-charts#1]
Hi Kevin,

I tried to install this project, but seems that it also have some dependencies 
        <parent>
                <groupId>quant.tipl</groupId>
                <artifactId>quant-tipl</artifactId>
                <version>1.0-SNAPSHOT</version>
                <relativePath>../pom.xml</relativePath>
         </parent>

```
    <dependency>
        <groupId>quant.tipl</groupId>
        <artifactId>tipl-core</artifactId>
        <version>${tipl.version}</version>
    </dependency>


    <dependency>
        <groupId>quant.tipl</groupId>
        <artifactId>tipl-spark</artifactId>
        <version>${tipl.version}</version>
    </dependency>
```

Can you please share parent projects too...

Thank you
Ankur

**Comment by kmader** [comment]
Version 1.0 of the project will have the dependencies integrated. TipL core can be made available but is very heavy

**Comment by ankurmitujjain** [comment]
Thanks Kevin, 
I would like to explore Version 1.0 and also would like to see Tipl-Core and Tipl-Spark...

Thanks
Ankur

**Comment by kmader** [comment]
Sorry for the very long delay the full code for tipl and all sub-packages is now available at https://github.com/kmader/TIPL
